[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120

[tool.poetry]
name = "zfs-replicate"
version = "1.4.0"
description = "ZFS Snapshot Replicator"
authors = [
  "Alex Brandt <alunduil@gmail.com>",
]
license = "BSD-2-Clause"
readme = "README.rst"
repository = "https://github.com/alunduil/zfs-replicate"
keywords = [
  "zfs",
  "replication",
  "backup",
  "remote",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: System",
  "Topic :: System :: Archiving",
  "Topic :: System :: Filesystems",
]
packages = [
  { include = "zfs" },
]

[tool.poetry.dependencies]
click = "^8.1.3"
python = "^3.7.2"
stringcase = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.5"
coveralls = "^2.1.1"
hypothesis = "^6.56.4"
pip = "^22.3"
pre-commit = "^2.7.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
vulture = "^2.0"

[tool.poetry.scripts]
zfs-replicate = "zfs.replicate.cli.main:main"

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=zfs --cov-report=term-missing"
testpaths = [
  "zfs_test",
]

[tool.skjold]
sources = [
  "pyup",
  "gemnasium",
]
